language: cpp
compiler: gcc
before_install:
    # Update packages
    - sudo apt-get update
    # Install cmake, git and build-essential
    - sudo apt-get install -y cmake build-essential
    # Install Python 3.7
    - sudo apt-get install -y python3-dev python3-numpy python3-py
    # Install dependencies for OpenCV
    sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev libeigen3-dev libglew-dev libgtk2.0-dev libgtk-3-dev libjpeg-dev libpng-dev libpostproc-dev libswscale-dev libtbb-dev libtiff5-dev libv4l-dev libxvidcore-dev libx264-dev zlib1g-dev pkg-config
    # Install GStreamer
    - sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
install:
    # Download OpenCV 4.1.0 source
    - wget https://github.com/opencv/opencv/archive/4.1.0.zip
    - wget https://github.com/opencv/opencv_contrib/archive/4.1.0.zip
    # Unzip source
    - unzip opencv.zip
    - unzip opencv_contrib.zip
    # Rename folder
    - mv opencv-4.1.0 opencv
    - mv opencv_contrib-4.1.0 opencv_contrib
    # Build OpenCV from source
    - mkdir build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_LIBV4L=ON -D WITH_V4L=ON -D WITH_GSTREAMER=ON -D WITH_GSTREAMER_0_10=OFF -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules ..
    - make
    # Install to OS
    - sudo make install
    - sudo ldconfig
script:
    - cmake .
